/*
 * TaskPane.java
 *
 * Created on October 21, 2008, 12:18 AM
 */

package magiccard;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;

import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JFrame;

import roomba.MagicCardRoombaPanel;
import magiccard.task.TaskController;

/**
 *
 * @author  erato
 */
public class TaskComponent extends javax.swing.JPanel {
    

	private int order = -1;
	private String label = "empty";
	private TaskController controller = null;
	private TaskManager parentManager = null;

	/** Creates new form TaskPane */
    public TaskComponent(String myLabel, TaskController controller, TaskManager manager) {
    	initComponents();
        this.controller = controller;
        parentManager = manager;
        setLabel(myLabel);
    }
    
    public void setOrder(int myOrder){
    	this.order = myOrder;
    }
    
    public int getOrder(){
    	return this.order;
    }
    
	public TaskManager getParentManager() {
		return parentManager;
	}

	public void setParentManager(TaskManager parentManager) {
		this.parentManager = parentManager;
	}
	
    public String getLabel() {
		return label;
	}

	public void setLabel(String label) {
		this.label = label;
		jLabel1.setText(label);
		//repaint();
	}

	public TaskController getController() {
		return controller;
	}

	public void setController(TaskController controller) {
		this.controller = controller;
	}
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

    	this.setPreferredSize(new Dimension(200,100));
    	this.setBorder(BorderFactory.createLineBorder(Color.black));
        jLabel1 = new javax.swing.JLabel();
        jComp1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jLabel1.setText(label);
        add(jLabel1);

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jComp1);
        jComp1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(38, 38, 38)
                .addComponent(jButton2)
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(209, Short.MAX_VALUE))
        );

        add(jComp1);
    }// </editor-fold>
    

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    	// TODO add your handling code here:
    		if(parentManager!=null && controller != null){
    			parentManager.startTaskByOrder(order);
    		}
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
    	// TODO add your handling code here:
    	if(parentManager!=null && controller != null){
			parentManager.cancelTaskByOrder(order);
		}
    }
    
    
    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComponent jComp1;
    // End of variables declaration
    
    /**
     * Testing code here
     */
    public static void main(String[] args){
    			
		TaskComponent tComp = new TaskComponent("task 1", null, null);
		
		TaskComponent tComp1 = new TaskComponent("task 2", null, null);

		Box aBox = new Box(BoxLayout.Y_AXIS);
		aBox.add(tComp);
		aBox.add(tComp1);
		JFrame frame = new JFrame();
	     
        // Add button to the frame.
        frame.getContentPane().add(aBox, BorderLayout.CENTER);
   
        // Set initial size.
        frame.setSize(300,300);
    
        // Show the frame.
        frame.setVisible(true);
    	
    }
    
}
